name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Update application.yml spring.config.import
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: ./src/main/resources/application.yml
          propertyPath: 'spring.config.import'
          value: 'classpath:application.yml'
          commitChange: false
          createPR: false

      - name: Update application.yml google.client-id
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: ./src/main/resources/application.yml
          propertyPath: 'spring.security.oauth2.client.registration.google["client-id"]'
          value: 'dummy'
          commitChange: false
          createPR: false

      - name: Update application.yml google.client-secret
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: ./src/main/resources/application.yml
          propertyPath: 'spring.security.oauth2.client.registration.google["client-secret"]'
          value: 'dummy'
          commitChange: false
          createPR: false

      - name: Build with Gradle Wrapper
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew build
